/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hash_store1;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ab o da
 */
public class MultiSalesTable extends javax.swing.JFrame {

    /**
     * Creates new form multiSales
     */
    DefaultTableModel multi;
    public MultiSalesTable( ) {
        initComponents();
        Home.styleTable (new JTable[] {multiSalesTable}) ;
         multi = createTableCols(multiSalesTable, new String[]{"ID", "Item", "Quantity", "Price"});
         shows();
    }

    
    DefaultTableModel createTableCols(JTable table, String[] cols) {
        DefaultTableModel dmodel;
        dmodel = (DefaultTableModel) table.getModel();
        for (int i = 0; i < cols.length; i++) {
            dmodel.addColumn(cols[i]);
        }
        return dmodel;
    }
    void shows(){
//         if (multi.getRowCount() != 0) {
//            for (int i = multi.getRowCount() - 1; i >= 0; i--) {
//                multi.removeRow(i);
//            }
//        }
        String  quant1 = null,  price = null;
        int id1;
        String sql3 = null;
        DBcon d = new DBcon();
        Home frame = new Home();
        id1 = frame.Idflag;
        String sql2 = "SELECT * FROM `multisales` WHERE ID = "+id1+";";
        try {
            String item = null;
            d.rs = d.st.executeQuery(sql2);
            int temp;
            while (d.rs.next()) {
                    quant1 = String.valueOf(d.rs.getInt("Quant"));
                    item = d.rs.getString("Item");
                    price = String.valueOf(d.rs.getFloat("Price"));
                String[] rowData = {String.valueOf(id1), item,quant1, price};
                multi.addRow(rowData);
            }
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "please try again   --  الرجاء المحاولة مرة أخري" );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        multiSalesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        multiSalesTable.setAutoCreateRowSorter(true);
        multiSalesTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multiSalesTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multiSalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        multiSalesTable.setGridColor(new java.awt.Color(153, 153, 153));
        multiSalesTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        multiSalesTable.setRowHeight(45);
        multiSalesTable.setShowHorizontalLines(true);
        multiSalesTable.setShowVerticalLines(false);
        jScrollPane3.setViewportView(multiSalesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiSalesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiSalesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiSalesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiSalesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiSalesTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable multiSalesTable;
    // End of variables declaration//GEN-END:variables
}
